[package]
name = "rust_compressor"
version = "0.2.0"

[dependencies]
chashmap = "2.2"
clap = "2.32"
itertools = "0.7"
polytype = "6.0"
programinduction = { version = "0.7.4" , features = [ "verbose" ] }
rayon = "1.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
